/**
  ******************************************************************************
  * @file    gsw145.c
  * @brief   Minimal driver for the MaxLinear GSW145 Ethernet switch.
  *
  * Every register value below is decoded from
  * Document/620246_GSW145_DS_Rev1.4.pdf Rev 1.4; the page numbers in the
  * comments refer to that document.
  ******************************************************************************
  */

#include "gsw145.h"
#include <stdio.h>

/* Diagnostics over USART1 (main.c retargets _write). */
#ifdef GSW145_NO_LOG
#define GSW145_LOG(...)   do { } while (0)
#else
#define GSW145_LOG(...)   printf(__VA_ARGS__)
#endif

extern ETH_HandleTypeDef heth;

/* -------------------------------------------------------------------------- */
/* SMDIO indirect access (data sheet p.41)                                     */
/* -------------------------------------------------------------------------- */
/* The switch answers on this MDIO address; it is fixed by pin strapping and is
   one of the values SMDIO_CFG.ADDR can take (0, 4, 0x10 or 0x1F - p.47). */
#define GSW145_SMDIO_ADDR         31U
/* Writing register 31 loads SMDIO_BADR, the base address of the target. */
#define GSW145_PTR_REG            31U
/* Register 0 then reads/writes the target at offset 0 from that base. */
#define GSW145_DATA_REG           0U

/* -------------------------------------------------------------------------- */
/* Register offsets and the values this board needs                            */
/* -------------------------------------------------------------------------- */

/* xMII Interface 5 Configuration (p.146). Reset value 0x2044: RGMII mode,
   interface isolated - so no RMII reference clock until we write this. */
#define GSW145_REG_MII_CFG_5      0xF100U
/*  0x40B3 = 0100 0000 1011 0011
 *    RST      [15]    = 0     reset released
 *    EN       [14]    = 1     interface enabled
 *    ISOL     [13]    = 0     not isolated
 *    CLKDIS   [12]    = 0     do NOT gate the clock when the link reads down
 *    CRS      [10:9]  = 00    PHY-mode only, irrelevant here
 *    RGMII_IBS[8]     = 0     RGMII in-band status off
 *    RMII     [7]     = 1     reference clock is an OUTPUT - the switch drives
 *                             the 50 MHz the MCU's RMII needs
 *    MIIRATE  [6:4]   = 011   50 MHz, mandatory in RMII mode
 *    MIIMODE  [3:0]   = 0011  RMII
 */
#define GSW145_MII_CFG5_RMII_50M  0x40B3U
#define GSW145_MII_CFG5_RST       0x8000U

/* PHY Address Register PORT 5 (p.176). Reset value 0x1805. */
#define GSW145_REG_PHY_ADDR_5     0xF410U
/*  0x2AA5 = 0010 1010 1010 0101
 *    AUTO_SEL [15]    = 0     use MDIO polling results as the "automatic" source
 *    LNKST    [14:13] = 01    link forced UP
 *    SPEED    [12:11] = 01    100 Mbps
 *    FDUP     [10:9]  = 01    full duplex
 *    FCONTX   [8:7]   = 01    pause enabled
 *    FCONRX   [6:5]   = 01    pause enabled
 *    ADDR     [4:0]   = 00101 PHY address 5, the reset default
 *
 *  This is the data sheet's own self-start value for port 5 (0x32A5, p.46/47)
 *  with SPEED changed from 1 Gbps to 100 Mbps. Earlier bring-up used 0x2BF5,
 *  which additionally moved ADDR from 5 to 21 and disabled pause - neither was
 *  intended.
 */
#define GSW145_PHY_ADDR5_100M_FDX 0x2AA5U

/* MDC Master Configuration Register 0 (p.162). Reset value 0x006F: the polling
   state machine is enabled on ports 0,1,2,3,5,6. */
#define GSW145_REG_MMDC_CFG_0     0xF40BU
#define GSW145_MMDC_CFG0_PORT5    (1U << 5)

/* -------------------------------------------------------------------------- */

HAL_StatusTypeDef GSW145_ReadReg(uint16_t addr, uint16_t *val)
{
  uint32_t tmp = 0U;

  if (val == NULL)
  {
    return HAL_ERROR;
  }

  if (HAL_ETH_WritePHYRegister(&heth, GSW145_SMDIO_ADDR, GSW145_PTR_REG, addr) != HAL_OK)
  {
    return HAL_ERROR;
  }
  if (HAL_ETH_ReadPHYRegister(&heth, GSW145_SMDIO_ADDR, GSW145_DATA_REG, &tmp) != HAL_OK)
  {
    return HAL_ERROR;
  }

  *val = (uint16_t)(tmp & 0xFFFFU);
  return HAL_OK;
}

HAL_StatusTypeDef GSW145_WriteReg(uint16_t addr, uint16_t val)
{
  if (HAL_ETH_WritePHYRegister(&heth, GSW145_SMDIO_ADDR, GSW145_PTR_REG, addr) != HAL_OK)
  {
    return HAL_ERROR;
  }
  if (HAL_ETH_WritePHYRegister(&heth, GSW145_SMDIO_ADDR, GSW145_DATA_REG, val) != HAL_OK)
  {
    return HAL_ERROR;
  }
  return HAL_OK;
}

HAL_StatusTypeDef GSW145_Init(void)
{
  uint16_t mii_cfg_before = 0U;
  uint16_t mmdc_cfg = 0U;
  uint16_t readback = 0U;
  HAL_StatusTypeDef status;

  /* Forces a link-time reference to the canary in ethernetif.c. If that file
     has been regenerated by CubeMX the symbol is gone and this never links,
     which is how we find out before the board does. */
  if (Cleo_EthernetifIsCustomized != 1U)
  {
    GSW145_LOG("[GSW145] ethernetif.c customization missing\r\n");
    return HAL_ERROR;
  }

  GSW145_LOG("[GSW145] init\r\n");

  /* Read MII_CFG_5 before touching it. This is the only way to tell how the
     switch actually comes out of reset on this board:
       0x2044 / 0x6044 -> RGMII, no RMII clock yet, we must configure it here
       0x40B3          -> already configured, e.g. by an attached EEPROM
     If a cold boot reports 0x40B3 the ordering below is belt-and-braces; if it
     reports 0x2044 then configuring the switch before HAL_ETH_Init() is what
     makes a cold boot work at all. */
  status = GSW145_ReadReg(GSW145_REG_MII_CFG_5, &mii_cfg_before);
  if (status != HAL_OK)
  {
    /* No MDIO at all - wrong SMDIO address, MDC not toggling, or the switch is
       held in reset. Nothing below can work. */
    GSW145_LOG("[GSW145] MDIO read failed - switch unreachable\r\n");
    return HAL_ERROR;
  }
  GSW145_LOG("[GSW145] MII_CFG_5 at power-up: 0x%04X\r\n", mii_cfg_before);

  /* 1. Stop the auto-polling state machine on port 5.
   *
   *    PHY_ADDR_5 only takes effect "when autopolling in MMDC_CFG_0 is
   *    disabled" (p.176). Port 5 has no external PHY, so the polling FSM reads
   *    all-ones and reports "PHY inactive, link status 0" (p.37) - which can
   *    override the forced link state below and drop the link intermittently.
   *    Read-modify-write so any strapping-dependent bits are preserved. */
  if (GSW145_ReadReg(GSW145_REG_MMDC_CFG_0, &mmdc_cfg) != HAL_OK)
  {
    return HAL_ERROR;
  }
  mmdc_cfg &= (uint16_t)~GSW145_MMDC_CFG0_PORT5;
  if (GSW145_WriteReg(GSW145_REG_MMDC_CFG_0, mmdc_cfg) != HAL_OK)
  {
    return HAL_ERROR;
  }

  /* 2. Force port 5 to 100 Mbps full duplex with the link up. There is no
   *    auto-negotiation partner on a direct MAC-to-MAC trace, so both ends have
   *    to be told the same thing; the MAC side is pinned in low_level_init(). */
  if (GSW145_WriteReg(GSW145_REG_PHY_ADDR_5, GSW145_PHY_ADDR5_100M_FDX) != HAL_OK)
  {
    return HAL_ERROR;
  }

  /* 3. Switch the interface to RMII and start driving the 50 MHz clock.
   *
   *    Pulse MII_CFG_5.RST around the change: the port is moving from RGMII to
   *    RMII, and RST re-initialises the xMII hardware while keeping the register
   *    contents (p.146). Without it the block can keep running with the old
   *    mode's timing. */
  if (GSW145_WriteReg(GSW145_REG_MII_CFG_5,
                      (uint16_t)(GSW145_MII_CFG5_RMII_50M | GSW145_MII_CFG5_RST)) != HAL_OK)
  {
    return HAL_ERROR;
  }
  HAL_Delay(2);
  if (GSW145_WriteReg(GSW145_REG_MII_CFG_5, GSW145_MII_CFG5_RMII_50M) != HAL_OK)
  {
    return HAL_ERROR;
  }

  /* Let the reference clock start and settle before the caller runs
     HAL_ETH_Init(), whose DMA software reset depends on it. */
  HAL_Delay(10);

  /* Verify, so a silent MDIO failure cannot masquerade as a working link. */
  if (GSW145_ReadReg(GSW145_REG_MII_CFG_5, &readback) != HAL_OK)
  {
    return HAL_ERROR;
  }
  GSW145_LOG("[GSW145] MII_CFG_5 = 0x%04X (expect 0x%04X)\r\n",
             readback, GSW145_MII_CFG5_RMII_50M);
  if (readback != GSW145_MII_CFG5_RMII_50M)
  {
    GSW145_LOG("[GSW145] MII_CFG_5 mismatch\r\n");
    return HAL_ERROR;
  }

  if (GSW145_ReadReg(GSW145_REG_PHY_ADDR_5, &readback) != HAL_OK)
  {
    return HAL_ERROR;
  }
  GSW145_LOG("[GSW145] PHY_ADDR_5 = 0x%04X (expect 0x%04X)\r\n",
             readback, GSW145_PHY_ADDR5_100M_FDX);
  if (readback != GSW145_PHY_ADDR5_100M_FDX)
  {
    GSW145_LOG("[GSW145] PHY_ADDR_5 mismatch\r\n");
    return HAL_ERROR;
  }

  GSW145_LOG("[GSW145] port 5 forced 100M/FDX, RMII clock out\r\n");
  return HAL_OK;
}

/* ========================================================================== */
/* Internal GPHY access over the switch's MDIO master interface               */
/* ========================================================================== */

/* MDIO master proxy (p.160-161). A PHY register is not part of the switch's
   own address space; the switch issues an MDIO frame on its master bus on our
   behalf. */
#define GSW145_REG_MMDIO_CTRL     0xF408U
#define GSW145_REG_MMDIO_READ     0xF409U
#define GSW145_REG_MMDIO_WRITE    0xF40AU
#define GSW145_MMDIO_MBUSY        (1U << 12)
#define GSW145_MMDIO_OP_WR        (1U << 10)   /* OP[11:10] = 01 */
#define GSW145_MMDIO_OP_RD        (2U << 10)   /* OP[11:10] = 10 */

/* PHY_ADDR_0 is the highest offset and the ports count downwards, so port N
   lives at PHY_ADDR_0 - N (p.135: F415 = port 0 ... F412 = port 3). */
#define GSW145_REG_PHY_ADDR_0     0xF415U
#define GSW145_PHY_ADDR_ADDR_MASK 0x001FU

/* PHY MDIO register offsets (p.280). */
#define GSW145_PHY_REG_MIISTAT    0x18U        /* negotiated speed/duplex   */
#define GSW145_PHY_REG_TPGCTRL    0x1CU        /* test-packet generator     */

/* MIISTAT fields (p.307). */
#define GSW145_MIISTAT_DPX        (1U << 3)
#define GSW145_MIISTAT_SPEED_MASK 0x0003U
#define GSW145_MIISTAT_SPEED_10   0x0000U
#define GSW145_MIISTAT_SPEED_100  0x0001U
#define GSW145_MIISTAT_SPEED_1000 0x0002U

/* TPGCTRL, offset 0x1C (p.313-315).
 *
 *  0x0450 = 0000 0100 0101 0000
 *    CHSEL    [15:14] = 00    channel A, unused outside debug dumping
 *    MODE     [13]    = 0     CONTINUOUS - keep sending until stopped
 *    BURST4EN [12]    = 0     no 4-packet debug bursts
 *    IPGL     [11:10] = 01    96 bit-time inter-packet gap, the IEEE minimum.
 *                             00 would be 48 BT, below spec, and a receiver is
 *                             entitled to drop the frames.
 *    TYPE     [9:8]   = 00    RANDOM payload
 *    SIZE     [6:4]   = 101   1518-byte frames, the largest non-jumbo size, so
 *                             the per-frame overhead is as small as it gets
 *    MOPT     [3:2]   = 00
 *    START    [1]     = 0     set separately, after EN
 *    EN       [0]     = 0     set first
 *
 *  1518 bytes of frame + 8 preamble/SFD + 12 gap = 1538 on the wire, so a
 *  1000BASE-T link carries 1518/1538 = 98.7% of 1 Gbit/s, about 987 Mbit/s.
 */
#define GSW145_TPGCTRL_BASE       0x0450U
#define GSW145_TPGCTRL_EN         (1U << 0)
#define GSW145_TPGCTRL_START      (1U << 1)

/* MMDC_CFG_0 polling-enable bit for an arbitrary port. */
#define GSW145_MMDC_CFG0_PORT(p)  ((uint16_t)(1U << (p)))

/**
  * @brief  Wait for the MDIO master to finish whatever it is doing.
  *
  * The auto-polling state machine shares this bus, so a transaction can already
  * be in flight when we arrive.
  */
static HAL_StatusTypeDef GSW145_MmdioWaitIdle(void)
{
  uint32_t start = HAL_GetTick();
  uint16_t ctrl = 0U;

  for (;;)
  {
    if (GSW145_ReadReg(GSW145_REG_MMDIO_CTRL, &ctrl) != HAL_OK)
    {
      return HAL_ERROR;
    }
    if ((ctrl & GSW145_MMDIO_MBUSY) == 0U)
    {
      return HAL_OK;
    }
    if ((HAL_GetTick() - start) > 20U)
    {
      GSW145_LOG("[GSW145] MDIO master stuck busy\r\n");
      return HAL_TIMEOUT;
    }
  }
}

HAL_StatusTypeDef GSW145_PhyWrite(uint8_t phy_addr, uint8_t reg, uint16_t val)
{
  uint16_t ctrl;

  if (GSW145_MmdioWaitIdle() != HAL_OK)
  {
    return HAL_TIMEOUT;
  }

  /* The data register must be loaded before the command that consumes it. */
  if (GSW145_WriteReg(GSW145_REG_MMDIO_WRITE, val) != HAL_OK)
  {
    return HAL_ERROR;
  }

  ctrl = (uint16_t)(GSW145_MMDIO_OP_WR
                    | ((uint16_t)(phy_addr & 0x1FU) << 5)
                    | (uint16_t)(reg & 0x1FU));
  if (GSW145_WriteReg(GSW145_REG_MMDIO_CTRL, ctrl) != HAL_OK)
  {
    return HAL_ERROR;
  }

  return GSW145_MmdioWaitIdle();
}

HAL_StatusTypeDef GSW145_PhyRead(uint8_t phy_addr, uint8_t reg, uint16_t *val)
{
  uint16_t ctrl;

  if (val == NULL)
  {
    return HAL_ERROR;
  }
  if (GSW145_MmdioWaitIdle() != HAL_OK)
  {
    return HAL_TIMEOUT;
  }

  ctrl = (uint16_t)(GSW145_MMDIO_OP_RD
                    | ((uint16_t)(phy_addr & 0x1FU) << 5)
                    | (uint16_t)(reg & 0x1FU));
  if (GSW145_WriteReg(GSW145_REG_MMDIO_CTRL, ctrl) != HAL_OK)
  {
    return HAL_ERROR;
  }

  /* Data is only valid once the switch has clocked the frame out and back. */
  if (GSW145_MmdioWaitIdle() != HAL_OK)
  {
    return HAL_TIMEOUT;
  }

  return GSW145_ReadReg(GSW145_REG_MMDIO_READ, val);
}

HAL_StatusTypeDef GSW145_GetPortPhyAddr(uint8_t port, uint8_t *phy_addr)
{
  uint16_t reg = 0U;

  if ((port >= GSW145_GPHY_PORT_COUNT) || (phy_addr == NULL))
  {
    return HAL_ERROR;
  }
  if (GSW145_ReadReg((uint16_t)(GSW145_REG_PHY_ADDR_0 - port), &reg) != HAL_OK)
  {
    return HAL_ERROR;
  }

  *phy_addr = (uint8_t)(reg & GSW145_PHY_ADDR_ADDR_MASK);
  return HAL_OK;
}

HAL_StatusTypeDef GSW145_GetPortLink(uint8_t port, uint16_t *speed_mbps,
                                     uint8_t *full_duplex)
{
  uint8_t phy_addr = 0U;
  uint16_t miistat = 0U;

  if ((speed_mbps == NULL) || (full_duplex == NULL))
  {
    return HAL_ERROR;
  }
  if (GSW145_GetPortPhyAddr(port, &phy_addr) != HAL_OK)
  {
    return HAL_ERROR;
  }
  if (GSW145_PhyRead(phy_addr, GSW145_PHY_REG_MIISTAT, &miistat) != HAL_OK)
  {
    return HAL_ERROR;
  }

  switch (miistat & GSW145_MIISTAT_SPEED_MASK)
  {
    case GSW145_MIISTAT_SPEED_10:   *speed_mbps = 10U;   break;
    case GSW145_MIISTAT_SPEED_100:  *speed_mbps = 100U;  break;
    case GSW145_MIISTAT_SPEED_1000: *speed_mbps = 1000U; break;
    default:                        *speed_mbps = 0U;    break;  /* FRE mode */
  }
  *full_duplex = ((miistat & GSW145_MIISTAT_DPX) != 0U) ? 1U : 0U;

  return HAL_OK;
}

/**
  * @brief  Suspend or resume the auto-polling state machine for one port.
  *
  * The polling FSM drives the same MDIO master bus we are about to use, and
  * p.37 warns that polling clears latching status bits underneath software.
  * Parking it for the port under test keeps the TPG writes deterministic.
  */
static HAL_StatusTypeDef GSW145_SetPortPolling(uint8_t port, uint8_t enable)
{
  uint16_t cfg = 0U;

  if (GSW145_ReadReg(GSW145_REG_MMDC_CFG_0, &cfg) != HAL_OK)
  {
    return HAL_ERROR;
  }
  if (enable != 0U)
  {
    cfg |= GSW145_MMDC_CFG0_PORT(port);
  }
  else
  {
    cfg &= (uint16_t)~GSW145_MMDC_CFG0_PORT(port);
  }
  return GSW145_WriteReg(GSW145_REG_MMDC_CFG_0, cfg);
}

HAL_StatusTypeDef GSW145_TpgStart(uint8_t port)
{
  uint8_t phy_addr = 0U;
  uint8_t full_duplex = 0U;
  uint16_t speed = 0U;
  uint16_t readback = 0U;

  if (port >= GSW145_GPHY_PORT_COUNT)
  {
    GSW145_LOG("[TPG] port %u has no internal PHY (use 0-3)\r\n",
               (unsigned)port);
    return HAL_ERROR;
  }

  if (GSW145_GetPortPhyAddr(port, &phy_addr) != HAL_OK)
  {
    GSW145_LOG("[TPG] cannot read PHY address for port %u\r\n", (unsigned)port);
    return HAL_ERROR;
  }

  /* Refuse to "measure 1 Gbit/s" on a link that is not running at 1 Gbit/s. */
  if (GSW145_GetPortLink(port, &speed, &full_duplex) != HAL_OK)
  {
    return HAL_ERROR;
  }
  if (speed == 0U)
  {
    GSW145_LOG("[TPG] port %u has no link - plug the cable into the PC\r\n",
               (unsigned)port);
    return HAL_ERROR;
  }
  if (speed != 1000U)
  {
    GSW145_LOG("[TPG] port %u linked at %u Mbps %s, not 1000BASE-T\r\n",
               (unsigned)port, (unsigned)speed, full_duplex ? "FDX" : "HDX");
    GSW145_LOG("[TPG] check the cable (needs all 4 pairs) and the PC NIC\r\n");
    return HAL_ERROR;
  }

  GSW145_LOG("[TPG] port %u (PHY %u) linked 1000BASE-T %s\r\n",
             (unsigned)port, (unsigned)phy_addr, full_duplex ? "FDX" : "HDX");

  (void)GSW145_SetPortPolling(port, 0U);

  /* Enable first, then start - the two bits are documented separately. */
  if (GSW145_PhyWrite(phy_addr, GSW145_PHY_REG_TPGCTRL,
                      GSW145_TPGCTRL_BASE | GSW145_TPGCTRL_EN) != HAL_OK)
  {
    GSW145_LOG("[TPG] enable failed\r\n");
    (void)GSW145_SetPortPolling(port, 1U);
    return HAL_ERROR;
  }
  if (GSW145_PhyWrite(phy_addr, GSW145_PHY_REG_TPGCTRL,
                      GSW145_TPGCTRL_BASE | GSW145_TPGCTRL_EN
                      | GSW145_TPGCTRL_START) != HAL_OK)
  {
    GSW145_LOG("[TPG] start failed\r\n");
    (void)GSW145_SetPortPolling(port, 1U);
    return HAL_ERROR;
  }

  if (GSW145_PhyRead(phy_addr, GSW145_PHY_REG_TPGCTRL, &readback) == HAL_OK)
  {
    GSW145_LOG("[TPG] TPGCTRL = 0x%04X\r\n", readback);
  }

  GSW145_LOG("[TPG] running: 1518-byte frames, ~987 Mbps of payload\r\n");
  GSW145_LOG("[TPG] frames go to 00-03-19-FF-FF-Fx, so capture the PC NIC in\r\n");
  GSW145_LOG("[TPG] promiscuous mode (Wireshark) or the NIC will discard them\r\n");
  return HAL_OK;
}

HAL_StatusTypeDef GSW145_TpgStop(uint8_t port)
{
  uint8_t phy_addr = 0U;
  HAL_StatusTypeDef status;

  if (port >= GSW145_GPHY_PORT_COUNT)
  {
    return HAL_ERROR;
  }
  if (GSW145_GetPortPhyAddr(port, &phy_addr) != HAL_OK)
  {
    return HAL_ERROR;
  }

  /* Drop START before EN, mirroring the start order. */
  status = GSW145_PhyWrite(phy_addr, GSW145_PHY_REG_TPGCTRL,
                           GSW145_TPGCTRL_BASE | GSW145_TPGCTRL_EN);
  if (status == HAL_OK)
  {
    status = GSW145_PhyWrite(phy_addr, GSW145_PHY_REG_TPGCTRL,
                             GSW145_TPGCTRL_BASE);
  }

  (void)GSW145_SetPortPolling(port, 1U);

  GSW145_LOG("[TPG] port %u stopped\r\n", (unsigned)port);
  return status;
}
